### PR TITLE
version the config.yaml sample file

### PR DESCRIPTION
**Pull request by rberrelleza**

### CODE REVIEW

**Review by pchico83 — APPROVED** [review]

**Comment by rberrelleza** [comment]
@huguestennier I don't think that last commit work as expected. When I go to https://deploy-preview-401--okteto-docs.netlify.app/docs/self-hosted/eks/,  the link points to https://deploy-preview-401--okteto-docs.netlify.app/docs/assets/files/config-b11601d552fc1d264e789325e910242c.yaml/, and when I download the file, it's called `download.yaml`. 

Is it not possible to include non-mdf files on this?

**Comment by rberrelleza** [comment]
> @huguestennier I don't think that last commit work as expected. When I go to https://deploy-preview-401--okteto-docs.netlify.app/docs/self-hosted/eks/, the link points to https://deploy-preview-401--okteto-docs.netlify.app/docs/assets/files/config-b11601d552fc1d264e789325e910242c.yaml/, and when I download the file, it's called `download.yaml`.
> 
> Is it not possible to include non-mdf files on this?

Is this a netlify issue or a docusaurus issue btw?

**Comment by huguestennier** [comment]
Just trying different thing :) I’ll ping you when it works

**Comment by rberrelleza** [comment]
@huguestennier any luck with this?

**Comment by huguestennier** [comment]
> @huguestennier any luck with this?

No luck, it seems to work when we link directly at the file but since with Docusarus the files goes through webpack, it doesn’t work. 

Thinking of workaround here, can we show the code directly on the page instead?

**Comment by omnomagonz** [comment]
@rberrelleza Do we still want to pursue this PR or could we close it for now?

**Comment by pchico83** [comment]
@rberrelleza should we close this one for now?

**Pull request closed without merging**
