### PR TITLE
Release 1.1

### PR DESCRIPTION
**Pull request by pchico83**

### CODE REVIEW

**Comment by rberrelleza** [comment]
Beautiful release, can't wait!

**Comment by maroshii** [comment]
Chart 1.1.0 has been published: https://artifacthub.io/packages/helm/okteto/okteto.

We should try to merge this when possible

**Comment by rberrelleza** [comment]
@pchico83 do you need help with this? we also need to create the actual version.

**Comment by maroshii** [comment]
Added 1.1 to versioned docs (docusaurus)

**Review by rberrelleza — APPROVED** [review]

**Pull request merged**
