### PR TITLE
reorganizing sidebar

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
WORK IN PROGRESS

### CODE REVIEW

**Comment by codyjlandstrom** [comment]
Love the new organization

**Comment by codyjlandstrom** [comment]
Converting to draft so it doesn't accidentally get merged

**Comment by pchico83** [comment]
@RinkiyaKeDad @codyjlandstrom, now that the developer onboarding guides are merged, should we close this PR?

**Comment by codyjlandstrom** [comment]
> @RinkiyaKeDad @codyjlandstrom, now that the developer onboarding guides are merged, should we close this PR?

A couple things I want to capture from Arsh's sidebar reorg. I'll create another PR to capture those and close this one shortly

**Comment by codyjlandstrom** [comment]
@pchico83 There's still some work here that Arsh did that I want to capture, just haven't been able to get to it yet. I'll aim to create a new PR soon so that we can close this one up.

**Pull request closed without merging**
